
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
    modId="clearwater" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Clear Water" #mandatory
    logoFile="logo.png" #optional
    credits="Elucent for the original mod/idea." #optional
    authors="ExpensiveKoala" #optional
    description='''
    See clearly under water!
    '''
[[dependencies.clearwater]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.clearmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
