
modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="MIT"
[[mods]] #mandatory
    modId="clearwater" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Clear Water" #mandatory
    logoFile="logo.png" #optional
    credits="Elucent for the original mod/idea." #optional
    authors="ExpensiveKoala" #optional
    description='''
    See clearly under water!
    '''
[[dependencies.clearwater]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.clearwater]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
